(function(B){function r(n){var f=r.modules[n];f||console.log("couldn't find module for: "+n);if(!f.exports){f.exports={};f.call(f.exports,f.exports,C(n))}return f.exports}function C(n){var f=n.replace(/[^\/]*$/,"");return function(g){g=(f+g).replace(/\/\.\//,"/").replace(/[^/]*\/\.\./,"").replace(/\/\//,"/");return r(g)}}if(!window.console){var A=["log","debug","info","warn","error","assert","dir","dirxml","group","groupEnd","time","timeEnd","count","trace","profile","profileEnd"];window.console=
{};for(var z=0;z<A.length;++z)window.console[A[z]]=function(){}}r.modules={};r.module=function(n,f){r.modules["./"+n]=f};r.module("base64",function(n){var f={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_=",encode_safe:function(g){var k="",a,e,b,m,o,l,c=0;for(g=f._utf8_encode(g);c<g.length;){a=g.charCodeAt(c++);e=g.charCodeAt(c++);b=g.charCodeAt(c++);m=a>>2;a=(a&3)<<4|e>>4;o=(e&15)<<2|b>>6;l=b&63;if(isNaN(e))o=l=64;else if(isNaN(b))l=64;k=k+f._keyStr.charAt(m)+f._keyStr.charAt(a)+
f._keyStr.charAt(o)+f._keyStr.charAt(l)}return k},decode_safe:function(g){var k="",a,e,b,m,o,l=0;for(g=g.replace(/[^A-Za-z0-9\-\_\=]/g,"");l<g.length;){a=f._keyStr.indexOf(g.charAt(l++));e=f._keyStr.indexOf(g.charAt(l++));m=f._keyStr.indexOf(g.charAt(l++));o=f._keyStr.indexOf(g.charAt(l++));a=a<<2|e>>4;e=(e&15)<<4|m>>2;b=(m&3)<<6|o;k+=String.fromCharCode(a);if(m!=64)k+=String.fromCharCode(e);if(o!=64)k+=String.fromCharCode(b)}return k=f._utf8_decode(k)},_utf8_encode:function(g){g=g.replace(/\r\n/g,
"\n");for(var k="",a=0;a<g.length;a++){var e=g.charCodeAt(a);if(e<128)k+=String.fromCharCode(e);else{if(e>127&&e<2048)k+=String.fromCharCode(e>>6|192);else{k+=String.fromCharCode(e>>12|224);k+=String.fromCharCode(e>>6&63|128)}k+=String.fromCharCode(e&63|128)}}return k},_utf8_decode:function(g){for(var k="",a=0,e=c1=c2=0;a<g.length;){e=g.charCodeAt(a);if(e<128){k+=String.fromCharCode(e);a++}else if(e>191&&e<224){c2=g.charCodeAt(a+1);k+=String.fromCharCode((e&31)<<6|c2&63);a+=2}else{c2=g.charCodeAt(a+
1);c3=g.charCodeAt(a+2);k+=String.fromCharCode((e&15)<<12|(c2&63)<<6|c3&63);a+=3}}return k}};n.base64=f});r.module("casti_ctrl_t",function(n,f){var g=f("./neoip_rpc_node");f("sys");var k=f("../vendor/underscore/underscore")._;k.noConflict();var a=function(e){var b=e.call_url||console.assert(false),m=e.casti_opts||console.assert(false),o=e.event_cb||function(){},l=e.req_timer_delay||500,c=e.verbose||0,h=null,d=null,i=function(){d!==null&&clearTimeout(d);d=null},j=function(){c>1&&console.log("req_timer expired. next in "+
l+"-msec");q()},p=null,q=function(){c>1&&console.log("rpc: rpc_call_request enter");console.assert(p===null);p=g.rpc_call.create({call_url:b,method_name:"request_stream",method_args:[m.mdata_srv_uri,m.cast_name,m.cast_privtext,m.scasti_uri,m.scasti_mod,m.http_peersrc_uri,m.web2srv_str],success_cb:function(u){w();i();var y=void 0;if(y==undefined)y=l;console.assert(d===null);d=setTimeout(j,y);if(u.length>0){h=u;s("ispublished",{cast_privhash:u})}else{h=null;s("nopublished",null)}},failure_cb:function(u){h=
null;c&&console.log("failure: "+f("sys").inspect(u));w();s("rpc_error",null)}})},t=function(){c>1&&console.log("rpc: rpc_call_release enter");console.assert(p===null);h=null;p=g.rpc_call.create({call_url:b,method_name:"release_stream",method_args:[m.mdata_srv_uri,m.cast_name,m.cast_privtext],success_cb:function(){w();s("released",null)},failure_cb:function(u){c&&console.log("failure: "+f("sys").inspect(u));w();s("rpc_error",null)}})},w=function(){p!==null&&p.destroy();p=null},x=null,v=null,s=function(u,
y){if(!(u==x&&k.isEqual(y,v))){v=y;x=u;o(u,y)}};q();return{release:function(){w();i();t()},published:function(){return h!==null},cast_privhash:function(){return h},destroy:function(){w();i()}}};a.create=function(e){return new a(e)};n.create=a.create});r.module("casto_testclient_t",function(n,f){var g=f("http"),k=function(a){console.assert(a.stream_url);var e=a.stream_url,b=a.event_cb||function(){},m=a.notify_unit||1024,o=a.verbose||0,l=a.idle_timer_delay||2E4,c=a.max_recved_len||null,h=null,d=function(){o>
1&&console.log("launch idle_timer timeout in "+l+"-msec");h=setTimeout(j,l)},i=function(){h!==null&&clearTimeout(h);h=null},j=function(){o&&console.log("idle timer expired. next in "+l+"-msec");b("error","idle timeout after "+l+"-msec")},p=null;(function(){var q=0,t=0,w=f("url").parse(e),x=g.createClient(w.port||80,w.hostname);x.on("error",function(v){b("error",v.message)});x.on("timeout",function(v){b("error",v.message)});p=x.request("GET",w.pathname,{host:w.host});p.on("response",function(v){o&&
console.log("Connected to "+e);d();if(v.statusCode!=200)b("error","statusCode="+v.statusCode);else{b("cnx_begin",null);v.on("data",function(s){o&&console.log("idle_time_refresh");i();d();q+=s.length;s=Math.floor(t/m);s=Math.floor(q/m)-s;s>0&&b("recved_size",s);t=q;c&&q>=c&&b("recved_len_maxed",null)});v.on("end",function(){o&&console.log("Connection ended");b("cnx_closed",null)})}});p.end()})();return{destroy:function(){i();p.connection.destroy()}}};k.create=function(a){return new k(a)};n.create=
k.create});r.module("collection",function(n){n.collection=function(){var f={},g=function(e,b){for(var m=e.split("/"),o=f,l=m[0],c=0;c<m.length-1;c++){typeof o[l]=="undefined"&&b(o,l);o=o[l];l=m[c+1]}return{submap:o,subkey:l}},k=function(e){console.assert(a(e));var b=g(e,function(m,o){throw Error("subkey "+o+" (from key "+e+") doesnt exist");});return b.submap[b.subkey]},a=function(e){var b=null;try{b=g(e,function(o,l){throw Error("subkey "+l+" (from key "+e+") doesnt exist");})}catch(m){return false}if(typeof b.submap[b.subkey]==
"undefined")return false;return true};return{set:function(e,b){var m=g(e,function(o,l){o[l]={}});m.submap[m.subkey]=b},get:k,get_dfl:function(e,b){return a(e)?k(e):b},del:function(e){console.assert(a(e));var b=g(e,function(m,o){throw Error("subkey "+o+" (from key "+e+") doesnt exist");});delete b.submap[b.subkey]},has:a}}});r.module("neoip_app_detect",function(n,f){var g=typeof process=="object"?f("./neoip_rpc_node").rpc_call:f("./neoip_rpc_web").rpc_call,k={oload:{port_beg:4550,port_end:4553},casto:{port_beg:4560,
port_end:4563},casti:{port_beg:4570,port_end:4573}},a={},e=function(d){return d in a},b=function(){a={}},m=function(d,i,j){console.assert(i);console.assert(d=="oload"||d=="casti"||d=="casto");j||(j=function(){});if(d in a){var p=a[d];p.version===false?setTimeout(function(){j(true)},0):setTimeout(function(){i(p.root_url,p.version)},0)}else{var q=k[d].port_end,t=k[d].port_beg,w=function(s){var u="http://127.0.0.1:"+t;a[d]={root_url:u,version:s};i(u,s)},x=function(){if(t==q){a[d]={version:false};j("not found")}else{t++;
v()}},v=function(){g.create({call_url:"http://127.0.0.1:"+t+"/neoip_"+d+"_appdetect_jsrest.js",method_name:"probe_apps",method_args:[],success_cb:w,failure_cb:x})};v()}},o=function(d,i){var j=d.match(/(\d+).(\d+).(\d+)/),p=i.match(/(\d+).(\d+).(\d+)/),q=parseInt(j[1],10),t=parseInt(p[1],10);if(q>t)return+1;if(q<t)return-1;q=parseInt(j[2],10);t=parseInt(p[2],10);if(q>t)return+1;if(q<t)return-1;j=parseInt(j[3],10);p=parseInt(p[3],10);if(j>p)return+1;if(j<p)return-1;return 0},l={oload:"0.0.1",casto:"0.0.1",
casti:"0.0.2"},c=function(){for(var d in l)if(!(d in a))return null;for(d in l)if(a[d].version===false)return"toinstall";for(d in l)if(o(a[d].version,l[d])<0)return"toupgrade";return"installed"},h=function(d){var i=function(){var p=c();p!=null&&d(p)};for(var j in l)m(j,i,i)};n.discover_app=m;n.discover_webpack=h;n.cache_contain=e;n.cache_get=function(d){return a[d]};n.cache_clear=b;n.avail=function(d){if(!e(d))return false;if(a[d].version==false)return false;return true};n.probe=m;n.webpack_probe=
h;n.webpack_avail=function(){return c=="installed"};n.webpack_status=c;n.clear=b});r.module("neoip_jsonp_call",function(n){var f=0;n.jsonp_call=function(g){var k=g.url||console.assert(g.url),a=g.success_cb||function(){},e=g.failure_cb||function(){},b="jsonp_call_cb_"+f++;console.assert(/callback=\?(&|$)/.test(k));k=k.replace("callback=?","callback="+b);var m=document.getElementsByTagName("head")[0],o=document.createElement("script"),l=function(){m.removeChild(o);window[b]=undefined;try{delete window[b]}catch(c){}};
window[b]=function(c){l();a(c)};o.src=k;o.onerror=function(){l();e("Network error")};m.appendChild(o);return{destroy:l}}});r.module("neoip_rpc_node",function(n,f){var g=f("http"),k=function(a){var e=a.call_url||console.assert(a.call_url),b=a.method_name||console.assert(a.method_name),m=a.method_args||[],o=a.success_cb||function(){},l=a.failure_cb||function(){},c=a.verbose||0,h=null;(function(){for(var d=f("url").parse(e),i=d.pathname+"?method_name="+b,j=0;j<m.length;j++)i+="&arg"+j+"="+escape(m[j]);
j=g.createClient(d.port||80,d.hostname);j.on("error",function(p){l({code:-1,string:p.message})});j.on("timeout",function(p){l({code:-1,string:p.message})});h=j.request("GET",i,{host:d.host});h.on("response",function(p){c&&console.log("STATUS: "+p.statusCode);c&&console.log("HEADERS: "+JSON.stringify(p.headers));if(p.statusCode!=200)return l(Error("http statuscode="+p.statuscode));p.setEncoding("utf8");p.on("data",function(q){c&&console.log("BODY: "+q);q=JSON.parse(q);if(q.fault){c>1&&console.dir(q);
l(q.fault)}else o(q.returned_val)})});h.end()})();return{destroy:function(){h.connection.destroy()}}};k.create=function(a){return new k(a)};n.rpc_call=k});r.module("neoip_rpc_web",function(n,f){var g=f("neoip_jsonp_call").jsonp_call,k=function(a){var e=a.call_url||console.assert(a.call_url),b=a.method_name||console.assert(a.method_name),m=a.method_args||[],o=a.success_cb||function(){},l=a.failure_cb||function(){},c=a.verbose||0,h=null;(function(){console.assert(h==null);for(var d=e+"?callback=?&method_name="+
b,i=0;i<m.length;i++)d+="&arg"+i+"="+escape(m[i]);c>1&&console.log("url="+d);h=new g({url:d,success_cb:function(j){c>1&&console.dir(j);j.fault?l(j.fault):o(j.returned_val)},failure_cb:function(j){c&&console.log("failed due to "+j);l(j)}})})();return{destroy:function(){h&&h.destroy();h=null}}};k.create=function(a){return new k(a)};n.rpc_call=k});r.module("url_builder_casto",function(n){n.create=function(f){console.assert(f.base_url);console.assert(f.cast_privhash);console.assert(f.cast_name);var g=
f.base_url+"/"+f.cast_privhash+"/"+f.cast_name;if(f.mdata_srv_uri)g+="?mdata_srv_uri="+escape(f.mdata_srv_uri);return g}});r.module("url_builder_oload_t",function(n,f){var g=f("./collection").collection,k=f("./base64").base64,a=function(e){var b=new g,m=function(c){for(var h=0;;h++){var d="outter_var/dupuri/"+h;if(!b.has(d)){b.set(d,c);break}}},o=function(){try{if(!b.has("outter_uri"))throw Error("No outter_uri");if(!b.has("inner_uri"))throw Error("No inner_uri");}catch(c){console.log("url_builder_oload_t not sane due to "+
c);return false}return true},l=function(c){var h=k.decode_safe,d=c.substr(0,c.indexOf("/http:/"));for(c=c.substr(c.indexOf("/http:/")+1);;){var i=d.substr(d.lastIndexOf("/")+1);if(i.substr(0,1)=="*"){var j=i.match(/\*(.+)\*(.+)$/);i=j[1];j=j[2];i!="dupuri"?b.set("outter_var/"+i,j):m(h(j))}else if(i=="raw"||i=="flv")b.set("outter_var/mod",i);else break;d=d.substr(0,d.lastIndexOf("/"))}b.set("outter_uri",d);h=[];if(c.lastIndexOf("?")!=-1){var p=c.substr(c.lastIndexOf("?")+1).split("&");for(d=0;d<p.length;d++){j=
p[d].split("=");i=j[0];j=j[1];if(i.indexOf("neoip_metavar_")!=0)h.push(p[d]);else{i=i.substr(14);b.set("minner_var/"+i,j)}}c=c.substr(0,c.lastIndexOf("?"))}if(b.has("outter_var/subfile_level")){j=b.get("outter_var/subfile_level");i=null;for(d=0;d<j;d++)i=i?c.lastIndexOf("/",i-1):c.lastIndexOf("/");d=c.substr(i);b.set("outter_var/subfile_path",d);b.del("outter_var/subfile_level");c=c.substr(0,i)}c=c;if(h.length>0)c+="?"+h.join("&");b.set("inner_uri",c)};e!==undefined&&l(e);return{outter_uri:function(c){b.set("outter_uri",
c)},inner_uri:function(c){b.set("inner_uri",c)},outter_var:function(c,h){return b.set("outter_var/"+c,h)},minner_var:function(c,h){return b.set("minner_var/"+c,h)},dupuri:m,set:function(c,h){b.set(c,h);return this},get:b.get,get_dfl:b.get_dfl,del:b.del,has:b.has,is_sane:o,to_string:function(){var c=k.encode_safe,h="";console.assert(o());h+=b.get("outter_uri")+"/";if(b.has("outter_var/mod"))h+=b.get("outter_var/mod")+"/";for(var d in b.get_dfl("outter_var",{}))if(d!="dupuri")if(d!="subfile_path")if(d!=
"mod"){h+="*"+d+"*";var i=b.get("outter_var/"+d);if(d=="http_peersrc_uri")i=url_encode_safe(i);h+=i;h+="/"}if(b.has("outter_var/subfile_path")){i=b.get("outter_var/subfile_path");i=i.split("/").length-1;h+="*subfile_level*"+i+"/"}for(var j in b.get_dfl("outter_var/dupuri",{})){h+="*dupuri*";h+=c(b.get("outter_var/dupuri/"+j));h+="/"}c=b.get("inner_uri");b.has("outter_var/subfile_path");i=b.get_dfl("outter_var/subfile_path",null);j=c.indexOf("?");h+=j!=-1?c.substr(0,j):c;if(i)h+=i;if(j!=-1)h+=c.substr(j,
c.length);for(d in b.get_dfl("minner_var",{})){h+=h.indexOf("?")==-1?"?":"&";h+="neoip_metavar_"+d+"="+escape(b.get("minner_var/"+d))}return h},from_string:l}};a.create=function(e){return new a(e)};n.url_builder_oload_t=a;n.create=a.create});r.module("webpeer",function(n,f){var g=f("./neoip_app_detect"),k=f("./url_builder_oload_t");webpeer_ready=function(a){g.webpack_probe(function(e){if(e=="toinstall")a(false);else if(e=="toupgrade")a(true);else e=="installed"?a(true):console.assert(false)})};webpeer_avail=
function(){return g.webpack_status()=="installed"};webpeer_url=function(a){if(!webpeer_avail())return a;return k.create(a).set("outter_uri",g.cache_get("oload").root_url).to_string()};n.ready=webpeer_ready;n.avail=webpeer_avail;n.url=webpeer_url});B.webpeer=r("./webpeer")})(window);
