(function(D){function s(o){var h=s.modules[o];if(!h)throw"couldn't find module for: "+o;if(!h.exports){h.exports={};h.call(h.exports,h.exports,E(o))}return h.exports}function E(o){var h=o.replace(/[^\/]*$/,"");return function(g){g=(h+g).replace(/\/\.\//,"/").replace(/[^/]*\/\.\./,"").replace(/\/\//,"/");return s(g)}}if(!window.console){var B=["log","debug","info","warn","error","assert","dir","dirxml","group","groupEnd","time","timeEnd","count","trace","profile","profileEnd"];window.console={};for(var z=
0;z<B.length;++z)window.console[B[z]]=function(){}}s.modules={};s.module=function(o,h){s.modules[o]=h};s.module("./base64",function(o){var h={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_=",encode_safe:function(g){var l="",a,c,b,m,n,k,d=0;for(g=h._utf8_encode(g);d<g.length;){a=g.charCodeAt(d++);c=g.charCodeAt(d++);b=g.charCodeAt(d++);m=a>>2;a=(a&3)<<4|c>>4;n=(c&15)<<2|b>>6;k=b&63;if(isNaN(c))n=k=64;else if(isNaN(b))k=64;l=l+h._keyStr.charAt(m)+h._keyStr.charAt(a)+h._keyStr.charAt(n)+
h._keyStr.charAt(k)}return l},decode_safe:function(g){var l="",a,c,b,m,n,k=0;for(g=g.replace(/[^A-Za-z0-9\-\_\=]/g,"");k<g.length;){a=h._keyStr.indexOf(g.charAt(k++));c=h._keyStr.indexOf(g.charAt(k++));m=h._keyStr.indexOf(g.charAt(k++));n=h._keyStr.indexOf(g.charAt(k++));a=a<<2|c>>4;c=(c&15)<<4|m>>2;b=(m&3)<<6|n;l+=String.fromCharCode(a);if(m!=64)l+=String.fromCharCode(c);if(n!=64)l+=String.fromCharCode(b)}return l=h._utf8_decode(l)},_utf8_encode:function(g){g=g.replace(/\r\n/g,"\n");for(var l="",
a=0;a<g.length;a++){var c=g.charCodeAt(a);if(c<128)l+=String.fromCharCode(c);else{if(c>127&&c<2048)l+=String.fromCharCode(c>>6|192);else{l+=String.fromCharCode(c>>12|224);l+=String.fromCharCode(c>>6&63|128)}l+=String.fromCharCode(c&63|128)}}return l},_utf8_decode:function(g){for(var l="",a=0,c=c1=c2=0;a<g.length;){c=g.charCodeAt(a);if(c<128){l+=String.fromCharCode(c);a++}else if(c>191&&c<224){c2=g.charCodeAt(a+1);l+=String.fromCharCode((c&31)<<6|c2&63);a+=2}else{c2=g.charCodeAt(a+1);c3=g.charCodeAt(a+
2);l+=String.fromCharCode((c&15)<<12|(c2&63)<<6|c3&63);a+=3}}return l}};o.base64=h});s.module("./casti_ctrl_t",function(o,h){h("sys");var g=h("../lib/neoip_rpc_node"),l=h("../vendor/node-helpers/equiv").equiv,a=function(c){var b=c.call_url||console.assert(false),m=c.casti_opts||console.assert(false),n=c.event_cb||function(){},k=c.req_timer_delay||500,d=c.verbose||0,i=null,e=null,f=function(){e!==null&&clearTimeout(e);e=null},j=function(){d>1&&console.log("req_timer expired. next in "+k+"-msec");q()},
p=null,q=function(){d>1&&console.log("rpc: rpc_call_request enter");console.assert(p===null);p=g.rpc_call.create({call_url:b,method_name:"request_stream",method_args:[m.mdata_srv_uri,m.cast_name,m.cast_privtext,m.scasti_uri,m.scasti_mod,m.http_peersrc_uri,m.web2srv_str],success_cb:function(w){t();f();var x=void 0;if(x==undefined)x=k;console.assert(e===null);e=setTimeout(j,x);if(w.length>0){i=w;v("ispublished",{cast_privhash:w})}else{i=null;v("nopublished",null)}},failure_cb:function(w){i=null;d&&
console.log("failure: "+h("sys").inspect(w));t();v("rpc_error",null)}})},u=function(){d>1&&console.log("rpc: rpc_call_release enter");console.assert(p===null);i=null;p=g.rpc_call.create({call_url:b,method_name:"release_stream",method_args:[m.mdata_srv_uri,m.cast_name,m.cast_privtext],success_cb:function(){t();v("released",null)},failure_cb:function(w){d&&console.log("failure: "+h("sys").inspect(w));t();v("rpc_error",null)}})},t=function(){p!==null&&p.destroy();p=null},y=null,r=null,v=function(w,x){if(!(w==
y&&l(x,r))){r=x;y=w;n(w,x)}};q();return{release:function(){t();f();u()},published:function(){return i!==null},cast_privhash:function(){return i},destroy:function(){t();f()}}};a.create=function(c){return new a(c)};o.create=a.create});s.module("./casto_testclient_t",function(o,h){var g=h("http"),l=function(a){console.assert(a.stream_url);var c=a.stream_url,b=a.event_cb||function(){},m=a.notify_unit||1024,n=a.verbose||0,k=a.idle_timer_delay||2E4,d=a.max_recved_len||null,i=null,e=function(){n>1&&console.log("launch idle_timer timeout in "+
k+"-msec");i=setTimeout(j,k)},f=function(){i!==null&&clearTimeout(i);i=null},j=function(){n&&console.log("idle timer expired. next in "+k+"-msec");b("error","idle timeout after "+k+"-msec")},p=null;(function(){var q=0,u=0,t=h("url").parse(c),y=g.createClient(t.port||80,t.hostname);y.on("error",function(r){b("error",r.message)});y.on("timeout",function(r){b("error",r.message)});p=y.request("GET",t.pathname,{host:t.host});p.on("response",function(r){n&&console.log("Connected to "+c);e();if(r.statusCode!=
200)b("error","statusCode="+r.statusCode);else{b("cnx_begin",null);r.on("data",function(v){n&&console.log("idle_time_refresh");f();e();q+=v.length;v=Math.floor(u/m);v=Math.floor(q/m)-v;v>0&&b("recved_size",v);u=q;d&&q>=d&&b("recved_len_maxed",null)});r.on("end",function(){n&&console.log("Connection ended");b("cnx_closed",null)})}});p.end()})();return{destroy:function(){f();p.connection.destroy()}}};l.create=function(a){return new l(a)};o.create=l.create});s.module("./collection",function(o){o.collection=
function(){var h={},g=function(c,b){for(var m=c.split("/"),n=h,k=m[0],d=0;d<m.length-1;d++){typeof n[k]=="undefined"&&b(n,k);n=n[k];k=m[d+1]}return{submap:n,subkey:k}},l=function(c){console.assert(a(c));var b=g(c,function(m,n){throw Error("subkey "+n+" (from key "+c+") doesnt exist");});return b.submap[b.subkey]},a=function(c){var b=null;try{b=g(c,function(n,k){throw Error("subkey "+k+" (from key "+c+") doesnt exist");})}catch(m){return false}if(typeof b.submap[b.subkey]=="undefined")return false;
return true};return{set:function(c,b){var m=g(c,function(n,k){n[k]={}});m.submap[m.subkey]=b},get:l,get_dfl:function(c,b){return a(c)?l(c):b},del:function(c){console.assert(a(c));var b=g(c,function(m,n){throw Error("subkey "+n+" (from key "+c+") doesnt exist");});delete b.submap[b.subkey]},has:a}}});s.module("./neoip_app_detect",function(o,h){var g=typeof process=="object"?h("./neoip_rpc_node").rpc_call:h("./neoip_rpc_web").rpc_call,l={oload:{port_beg:4550,port_end:4553},casto:{port_beg:4560,port_end:4563},
casti:{port_beg:4570,port_end:4573}},a={},c=function(e){return e in a},b=function(){a={}},m=function(e){var f=e.app_suffix||console.assert(e.app_suffix),j=e.success_cb||function(){},p=e.failure_cb||function(){},q=e.nocache||false,u=e.verbose||0;console.assert(f=="oload"||f=="casti"||f=="casto");p||(p=function(){});if(f in a&&!q){var t=a[f];t.version===false?setTimeout(function(){p(true)},0):setTimeout(function(){j(t.root_url,t.version)},0)}else{var y=l[f].port_end,r=l[f].port_beg,v=function(A){u&&
console.log("found "+f+" version "+A+" at port "+r);var C="http://127.0.0.1:"+r;a[f]={root_url:C,version:A};j(C,A)},w=function(){u&&console.log(f+" not found port_cur="+r);if(r==y){a[f]={version:false};p("not found")}else{r++;x()}},x=function(){g.create({call_url:"http://127.0.0.1:"+r+"/neoip_"+f+"_appdetect_jsrest.js",method_name:"probe_apps",method_args:[],success_cb:v,failure_cb:w})};x()}},n=function(e,f){var j=e.match(/(\d+).(\d+).(\d+)/),p=f.match(/(\d+).(\d+).(\d+)/),q=parseInt(j[1],10),u=parseInt(p[1],
10);if(q>u)return+1;if(q<u)return-1;q=parseInt(j[2],10);u=parseInt(p[2],10);if(q>u)return+1;if(q<u)return-1;j=parseInt(j[3],10);p=parseInt(p[3],10);if(j>p)return+1;if(j<p)return-1;return 0},k={oload:"0.0.1",casto:"0.0.1",casti:"0.0.2"},d=function(){for(var e in k)if(!(e in a))return null;for(e in k)if(a[e].version===false)return"toinstall";for(e in k)if(n(a[e].version,k[e])<0)return"toupgrade";return"installed"},i=function(e){var f=e.completed_cb||function(){};e=e.nocache||false;var j=3,p=function(){j-=
1;if(!(j>0)){var u=d();f(u)}};for(var q in k)m({app_suffix:q,nocache:e,success_cb:p,failure_cb:p})};o.discover_app=m;o.discover_webpack=i;o.cache_contain=c;o.cache_get=function(e){return a[e]};o.cache_clear=b;o.avail=function(e){if(!c(e))return false;if(a[e].version==false)return false;return true};o.probe=m;o.webpack_probe=i;o.webpack_avail=function(){return d()=="installed"};o.webpack_status=d;o.clear=b});s.module("./neoip_jsonp_call",function(o){var h=0;o.jsonp_call=function(g){var l=g.url||console.assert(g.url),
a=g.success_cb||function(){},c=g.failure_cb||function(){},b="jsonp_call_cb_"+h++;console.assert(/callback=\?(&|$)/.test(l));l=l.replace("callback=?","callback="+b);var m=document.getElementsByTagName("head")[0],n=document.createElement("script"),k=function(){m.removeChild(n);window[b]=undefined;try{delete window[b]}catch(d){}};window[b]=function(d){k();a(d)};n.src=l;n.onerror=function(){k();c("Network error")};m.appendChild(n);return{destroy:k}}});s.module("./neoip_rpc_node",function(o,h){var g=h("http"),
l=function(a){var c=a.call_url||console.assert(a.call_url),b=a.method_name||console.assert(a.method_name),m=a.method_args||[],n=a.success_cb||function(){},k=a.failure_cb||function(){},d=a.verbose||0,i=null;(function(){for(var e=h("url").parse(c),f=e.pathname+"?method_name="+b,j=0;j<m.length;j++)f+="&arg"+j+"="+escape(m[j]);j=g.createClient(e.port||80,e.hostname);j.on("error",function(p){k({code:-1,string:p.message})});j.on("timeout",function(p){k({code:-1,string:p.message})});i=j.request("GET",f,
{host:e.host});i.on("response",function(p){d&&console.log("STATUS: "+p.statusCode);d&&console.log("HEADERS: "+JSON.stringify(p.headers));if(p.statusCode!=200)return k(Error("http statuscode="+p.statuscode));p.setEncoding("utf8");p.on("data",function(q){d&&console.log("BODY: "+q);q=JSON.parse(q);if(q.fault){d>1&&console.dir(q);k(q.fault)}else n(q.returned_val)})});i.end()})();return{destroy:function(){i.connection.destroy()}}};l.create=function(a){return new l(a)};o.rpc_call=l});s.module("./neoip_rpc_web",
function(o,h){var g=h("neoip_jsonp_call").jsonp_call,l=function(a){var c=a.call_url||console.assert(a.call_url),b=a.method_name||console.assert(a.method_name),m=a.method_args||[],n=a.success_cb||function(){},k=a.failure_cb||function(){},d=a.verbose||0,i=null;(function(){console.assert(i==null);for(var e=c+"?callback=?&method_name="+b,f=0;f<m.length;f++)e+="&arg"+f+"="+escape(m[f]);d>1&&console.log("url="+e);i=new g({url:e,success_cb:function(j){d>1&&console.dir(j);j.fault?k(j.fault):n(j.returned_val)},
failure_cb:function(j){d&&console.log("failed due to "+j);k(j)}})})();return{destroy:function(){i&&i.destroy();i=null}}};l.create=function(a){return new l(a)};o.rpc_call=l});s.module("./url_builder_casto",function(o){o.create=function(h){console.assert(h.base_url);console.assert(h.cast_privhash);console.assert(h.cast_name);var g=h.base_url+"/"+h.cast_privhash+"/"+h.cast_name;if(h.mdata_srv_uri)g+="?mdata_srv_uri="+escape(h.mdata_srv_uri);return g}});s.module("./url_builder_oload_t",function(o,h){var g=
h("./collection").collection,l=h("./base64").base64,a=function(c){var b=new g,m=function(d){for(var i=0;;i++){var e="outter_var/dupuri/"+i;if(!b.has(e)){b.set(e,d);break}}},n=function(){try{if(!b.has("outter_uri"))throw Error("No outter_uri");if(!b.has("inner_uri"))throw Error("No inner_uri");}catch(d){console.log("url_builder_oload_t not sane due to "+d);return false}return true},k=function(d){var i=l.decode_safe,e=d.substr(0,d.indexOf("/http:/"));for(d=d.substr(d.indexOf("/http:/")+1);;){var f=
e.substr(e.lastIndexOf("/")+1);if(f.substr(0,1)=="*"){var j=f.match(/\*(.+)\*(.+)$/);f=j[1];j=j[2];f!="dupuri"?b.set("outter_var/"+f,j):m(i(j))}else if(f=="raw"||f=="flv")b.set("outter_var/mod",f);else break;e=e.substr(0,e.lastIndexOf("/"))}b.set("outter_uri",e);i=[];if(d.lastIndexOf("?")!=-1){var p=d.substr(d.lastIndexOf("?")+1).split("&");for(e=0;e<p.length;e++){j=p[e].split("=");f=j[0];j=j[1];if(f.indexOf("neoip_metavar_")!=0)i.push(p[e]);else{f=f.substr(14);b.set("minner_var/"+f,j)}}d=d.substr(0,
d.lastIndexOf("?"))}if(b.has("outter_var/subfile_level")){j=b.get("outter_var/subfile_level");f=null;for(e=0;e<j;e++)f=f?d.lastIndexOf("/",f-1):d.lastIndexOf("/");e=d.substr(f);b.set("outter_var/subfile_path",e);b.del("outter_var/subfile_level");d=d.substr(0,f)}d=d;if(i.length>0)d+="?"+i.join("&");b.set("inner_uri",d)};c!==undefined&&k(c);return{outter_uri:function(d){b.set("outter_uri",d)},inner_uri:function(d){b.set("inner_uri",d)},outter_var:function(d,i){return b.set("outter_var/"+d,i)},minner_var:function(d,
i){return b.set("minner_var/"+d,i)},dupuri:m,set:function(d,i){b.set(d,i);return this},get:b.get,get_dfl:b.get_dfl,del:b.del,has:b.has,is_sane:n,to_string:function(){var d=l.encode_safe,i="";console.assert(n());i+=b.get("outter_uri")+"/";if(b.has("outter_var/mod"))i+=b.get("outter_var/mod")+"/";for(var e in b.get_dfl("outter_var",{}))if(e!="dupuri")if(e!="subfile_path")if(e!="mod"){i+="*"+e+"*";var f=b.get("outter_var/"+e);if(e=="http_peersrc_uri")f=url_encode_safe(f);i+=f;i+="/"}if(b.has("outter_var/subfile_path")){f=
b.get("outter_var/subfile_path");f=f.split("/").length-1;i+="*subfile_level*"+f+"/"}for(var j in b.get_dfl("outter_var/dupuri",{})){i+="*dupuri*";i+=d(b.get("outter_var/dupuri/"+j));i+="/"}d=b.get("inner_uri");b.has("outter_var/subfile_path");f=b.get_dfl("outter_var/subfile_path",null);j=d.indexOf("?");i+=j!=-1?d.substr(0,j):d;if(f)i+=f;if(j!=-1)i+=d.substr(j,d.length);for(e in b.get_dfl("minner_var",{})){i+=i.indexOf("?")==-1?"?":"&";i+="neoip_metavar_"+e+"="+escape(b.get("minner_var/"+e))}return i},
from_string:k}};a.create=function(c){return new a(c)};o.url_builder_oload_t=a;o.create=a.create});s.module("./webpeer",function(o,h){var g=h("./neoip_app_detect"),l=h("./url_builder_oload_t"),a={};a.ready=function(c){g.webpack_probe({completed_cb:function(b){if(b=="toinstall")c(false);else if(b=="toupgrade")c(true);else b=="installed"?c(true):console.assert(false)}})};a.avail=function(){return g.webpack_status()=="installed"};a.url=function(c){if(!a.avail())return c;return l.create(c).set("outter_uri",
g.cache_get("oload").root_url).to_string()};a.monitor=function(c){if(typeof c=="function")c={completed_cb:c};var b=c.completed_cb||function(){},m=c.delay||1E3,n=null,k=function(){g.webpack_probe({completed_cb:function(d){if(d!=n){n=d;b(d)}setTimeout(k,m)},nocache:true})};setTimeout(k,0)};a.badge=function(){a.monitor(function(){var c=document.getElementById("webpeer_badge");c.src="http://webpeer.it/images/badge/"+(a.avail()?"accept.png":"exclamation.png");c.title=a.avail()?"You are a web peer. Welcome!":
"You are not yet a web peer. Click to be one."})};o.ready=a.ready;o.avail=a.avail;o.url=a.url;o.badge=a.badge});D.webpeer=s("./webpeer")})(window);
